# This CI job installs Crystal and shard dependencies, then executes `crystal spec` to run the test suite
# More configuration options are available at https://crystal-lang.github.io/install-crystal/configurator.html

name: Matrix Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - dev

concurrency:
  group: ${{ github.sha }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        crystal:
          - 1.0.0
          - latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install shards
        run: shards install --ignore-crystal-version
      - name: Run tests
        run: crystal spec --order=random
      - name: Build
        run: shards build
      - name: Check formatting
        run: crystal tool format; git diff --exit-code
        if: matrix.crystal == 'latest'
